// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/teachers/eval/{id}": {
            "get": {
                "description": "Get teacher evaluation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "Get teacher evaluation",
                "operationId": "get-teacher-eval",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Teacher ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.ResponseBase"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/responses.TeacherEvalResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/teachers/group/{group_name}": {
            "get": {
                "description": "Get group teachers list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "Get group teachers list",
                "operationId": "get-group-teachers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name group_name",
                        "name": "group_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.ResponseBase"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/responses.TeachersResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/teachers/set_mark/": {
            "post": {
                "description": "Set teachers mark",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "Set teachers mark",
                "operationId": "set-teacher-mark",
                "parameters": [
                    {
                        "description": "Mark payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/responses.TeacherMarkBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.ResponseBase"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/teachers/{filter}": {
            "get": {
                "description": "Get teachers list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "Get teachers list",
                "operationId": "get-teachers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name filter",
                        "name": "filter",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.ResponseBase"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/responses.TeachersResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/timetable/groups/": {
            "get": {
                "description": "Get all groups list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timetable"
                ],
                "summary": "Get groups list",
                "operationId": "get-groups",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.ResponseBase"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/responses.GroupResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/timetable/sessions/{group_name}": {
            "get": {
                "description": "Get session timetable by group name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timetable"
                ],
                "summary": "Get session timetable",
                "operationId": "get-group-session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Name",
                        "name": "group_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.ResponseBase"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/responses.SessionResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/timetable/timetables/{group_name}/{timetable_type}": {
            "get": {
                "description": "Get group timetable by group name and type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timetable"
                ],
                "summary": "Get group timetable",
                "operationId": "get-group-timetable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Name",
                        "name": "group_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "timetable type",
                        "name": "timetable_type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.ResponseBase"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/responses.TimetableResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/timetable/types/{group_name}": {
            "get": {
                "description": "Get timetable types by group name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timetable"
                ],
                "summary": "Get timetable types",
                "operationId": "get-timetable-types",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Name",
                        "name": "group_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.ResponseBase"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "responses.Evaluation": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "mark": {
                    "type": "number"
                }
            }
        },
        "responses.GroupResponse": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "string"
                },
                "faculty": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "responses.GroupSubject": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "subject_name": {
                    "type": "string"
                },
                "subject_type": {
                    "type": "string"
                },
                "teacher": {
                    "type": "string"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "responses.ResponseBase": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "result": {
                    "type": "boolean"
                }
            }
        },
        "responses.SessionResponse": {
            "type": "object",
            "properties": {
                "addition": {
                    "type": "string"
                },
                "group_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "table": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.SessionSubject"
                    }
                }
            }
        },
        "responses.SessionSubject": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "subject_name": {
                    "type": "string"
                },
                "subject_type": {
                    "type": "string"
                },
                "teacher": {
                    "type": "string"
                }
            }
        },
        "responses.TeacherEvalResponse": {
            "type": "object",
            "properties": {
                "average_mark": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                },
                "evaluations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.Evaluation"
                    }
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "responses.TeacherMarkBody": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "mark": {
                    "type": "integer"
                },
                "sid": {
                    "type": "integer"
                }
            }
        },
        "responses.TeachersResponse": {
            "type": "object",
            "properties": {
                "department": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "responses.TimetableResponse": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "integer"
                },
                "group_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "table": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.GroupSubject"
                    }
                },
                "week_num": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
